### PR TITLE
Fix Travis CI build; update repo and Docker file

### PR DESCRIPTION
**Pull request by gaborigloi**
It seems that the OCaml compiler version of the default `ocaml/opam`
Docker image has recently changed from 4.02.3 to 4.03.0. (See
https://github.com/ocaml/opam-dockerfiles/commit/a323bfc99bce6718b713df27942292983d4eab2e)
At the moment we do not support 4.03.0, only 4.02.3.

This commit explicitly fixes the OCaml version to 4.02.3, and uses the
Debian-based image (the default image is also based on Debian):
`ocaml/opam:debian-stable_ocaml-4.02.3`
(Alternatively I could specify the Debian release:
`ocaml/opam:debian-8_ocaml-4.02.3`)

This is required to make the Travis CI build work, since we use this
Docker image for testing the repository with Travis.

Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>

### CODE REVIEW

**Comment by lindig** [comment]
Travis CI failed. Is the failure unrelated to the change in the Docker image?

**Comment by mseri** [comment]
The failures are due to (at least) the fact that we are tracking head of mirage/shared-block-ring that has now been ported to use the `result` type. We need to change the URL to get the archive of 2.2.0 instead of master's HEAD.

**Comment by gaborigloi** [comment]
@mseri Sure, updated the pull request :). Unfortunately, when I tried installing the shared-block-ring package locally, it still return the error I mentioned:
```
ocamlfind: Package `sexplib.syntax' not found
```

Some of the failures are due to nbd, not shared-block-ring. Not sure why, since nbd's own Travis build [passes](https://github.com/xapi-project/nbd).

**Comment by gaborigloi** [comment]
Now it's looking much better!:) (https://travis-ci.org/gaborigloi/opam-repo-dev)
By the way, should I update the `opam` file of `shared-block-ring` to match that of the 2.2.0 release?

**Comment by mseri** [comment]
Yes please. Also can you have a look at what is the conflict between nbd and error in lwt? For `xcp-rrdd` it should be enough to add `inotify` to the dependencies in the opam file.

**Comment by gaborigloi** [comment]
Done, I think the error with `nbd` and `Lwt` was the same as the error with `shared-block-ring` and `Lwt`: incompatibilities with the new `result` type, that thew new version of `Lwt` uses.

However, there are other packages that use `Lwt` and work fine with the newest 2.6 version that uses `Result` and I'm not sure why.

**Comment by gaborigloi** [comment]
Now only xapi fails.

**Comment by gaborigloi** [comment]
After modifying the opam file of `xapi` to match the original one, it builds fine!

**Pull request merged**
